### PR TITLE
Bug-Fix(ui): optimize API fetching in About-us page

### LINKED ISSUE #59: bug: Enhance GitHub API Fetching Performance for Repo Stats
### Overview

We've identified a performance issue with our application's interaction with the GitHub API, specifically when fetching repository statistics. The current implementation is not retrieving data in a timely manner, which negatively impacts user experience and potentially affects our application's overall performance. This enhancement aims to optimize our API calls to github.com for repo stats, ensuring faster and more efficient data retrieval.

### Tasks

- [ ] Analyze current API call implementation
  - [ ] Review existing code for GitHub API calls
  - [ ] Identify potential bottlenecks in the current approach
  - [ ] Document findings and share below

- [ ] Investigate GitHub API rate limits and best practices
  - [ ] Review GitHub API documentation for rate limiting policies
  - [ ] Identify any endpoints that might be causing delays
  - [ ] Research best practices for efficient API usage
  - [ ] Investigate caching strategies for frequently accessed data

### PR DESCRIPTION
**Pull request by d-beloved**
Screenshot 2024-11-19 at 16 03 23

## Related Issues

- Fixes #59  (issue)

## Changes List

- [x] This change optimizes the About-Us page API fetching for better performance and reduced API calls to the GitHub public server

## Type of Changes

- [x] Bug fix (fixes an existing issue)

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

### CODE REVIEW

File: frontend/app/about/page.tsx [hunk 1]
```diff
@@ -1,134 +1,155 @@
...
-						<svg className="blur-3xl filter opacity-70" width="756" height="202" viewBox="0 0 756 202" fill="none" xmlns="http://www.w3.org/2000/svg">
-							<path d="M434.095 21.8754C619.918 21.8754 755.509 -33.413 755.509 31.8038C755.509 97.0206 268.41 201.855 82.5876 201.855C-103.234 201.855 82.5876 97.0207 82.5876 31.8039C82.5876 -33.4129 248.273 21.8754 434.095 21.8754Z" fill="url(#b)" />
-							<defs>
-								<linearGradient id="b" x1="0" y1="121.855" x2="8.92305" y2="-28.873" gradientUnits="userSpaceOnUse">
-									<stop offset="0%" style={{ stopColor: "var(--color-cyan-500)" }}></stop>
-									<stop offset="100%" style={{ stopColor: "var(--color-purple-300)" }}></stop>
-								</linearGradient>
-							</defs>
-						</svg>
+		<Suspense fallback={<div>Loading...</div>}>
```
Comment (d-beloved) [inline frontend/app/about/page.tsx:32]: No big file change here, I only wrapped the component in a "Suspense" to avoid a mismatch error caused by the component not waiting for the data to be available before rendering. [ref: here](https://github.com/vercel/next.js/discussions/36582)

Comment (JustinhSE) [reply frontend/app/about/page.tsx:32]: Thanks

**Comment by JustinhSE** [comment]
Before I merge, did you npm build this @d-beloved ?

**Comment by d-beloved** [comment]
Yes I did run that, it worked fine
